# Stage 1: Build Assets
FROM node:20-alpine as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Production Image
FROM php:8.3-fpm-alpine

# Install System Dependencies & Node.js (diperlukan untuk SSR)
RUN apk add --no-cache \
    libpng-dev libzip-dev zip unzip git curl oniguruma-dev libxml2-dev nodejs npm

# Install PHP Extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .
# Salin hasil build dari stage 1
COPY --from=build-stage /app/public/build ./public/build
COPY --from=build-stage /app/bootstrap/ssr ./bootstrap/ssr

# Set Permission
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]